
firstCharacter = input("Enter a character: ")
secondCharacter = input("Enter another character: ")
signedShortValue = int(input("Enter a signed short value: "))
unsignedShortValue = int(input("Enter an unsigned short value: "))
signedIntergerValue = int(input("Enter a signed integer value: "))
unsignedIntegerValue = int(input("Enter an unsigned integer value: "))
signedLongValue = int(input("Enter a signed long value: "))
unsignedLongValue = int(input("Enter an unsigned long value: "))
signedLongLongValue = int(input("Enter a signed long long value: "))
unsignedLongLongValue = int(input("Enter and unsigned long long vale: "))
floatValue = float(input("Enter a float value: "))
doubleValue = float(input("Enter a double value: "))
longDoubleValue = float(input("Enter a long double value: "))

print(f'You entered character: {firstCharacter}')
print(f'You entered unsigned character: {secondCharacter} ')
print(f'\nYou entered signed short: {signedShortValue} ')
print(f'You entered unsigned short: {unsignedShortValue}')
print(f'\nYou entered signed int: {signedIntergerValue}')
print(f'You entered unsigned int: {unsignedIntegerValue}')
print(f'\nYou have entered signed long: {signedLongValue}')
print(f'You have entered unsigned long: {unsignedLongValue}')
print(f'\nYou entered signed long long: {signedLongLongValue}')
print(f'You entered unsigned long long: {unsignedLongLongValue}')
print(f'\nYou entered float: {floatValue}')
print(f'You entered double: {doubleValue}')
print(f'You entered long double: {longDoubleValue}')